Fix writing dictionary to JSON file
Use
with open(filename, 'w') as file:
    file.write(json.dumps(dic))

Instead of
f = open(filename,"w")
f.write(output)

Error message
TypeError: Object of type type is not JSON serializable